name: Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Update to 18 if your project requires it

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Start server in the background
        run: |
          npm start &
          npx wait-on http://localhost:3001

      - name: Run Cypress tests
        run: npx cypress run